### ISSUE TITLE
Asset Tracking Reference Firmware

### ISSUE THREAD

**Issue by 0Grit** [golioth/samples#5]
- [x] Review current work in process to get a feel for how this can effect other sprint tasks
- [x] Review @mniestroj's existing sample
- [x] Get @mniestroj's opinion of effort
- [x] Decide if this makes it into this sprint

Existing work is here https://github.com/golioth/samples/pull/3

References:
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/applications/asset_tracker_v2/README.html
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/modem/location.html

**Comment by 0Grit** [comment]
We'll eventually want this running on a Thingy91 too.

**Comment by 0Grit** [comment]
@vitprajzler See #3 for the latest information. assessment is that getting this to lock onto a satellite in a reasonable time will not be straightforward.

Give me the word and I will adjust the status of this issue accordingly.

**Comment by vitprajzler** [comment]
Is there any subset of the A-GPS (aka quicker fix from user experience perspective) functionality we could deliver in this sprint? E.g. show we can get the AGPS data from the service and apply it (without getting all the way to a GPS fix)?

**Comment by 0Grit** [comment]
@vitprajzler, @ChrisGammell, @beriberikix
I did some further digging.

Assuming we were to create the simplest possible example: (No A-GPS)
 1. Turn on GPS
 2. Get GPS coordinates (30s - 3minutes)
 3. Turn off GPS
 4. Turn on LTE
 5. Connect to Golioth
 6. Send GPS coordinates
 7. Repeat

@mniestroj has indicated the least risk path to the above would be to create a bespoke application in order to understand how to manage the modem.

Sources of risk:
* The existing Nordic sample offloads DTLS to the modem which we currently do not support.
* The biggest sticking point will be to figure out how to manage the modem; turning LTE & GPS on and off. That effort would need some up front research and experimentation. (upto 1 week)
* The time to get this working would further push COAP abstraction into the next sprint

**Comment by beriberikix** [comment]
This is reasonable way to approach the problem and worth the effort in the long term.

Is this related to the demo ask as well? If so, A-GPS (i.e. using the 3P server) is the main ask. So if that's not feasible, I want to make sure we _don't_ rush this work for the demo.

Will follow up on slack for more details.

**Comment by 0Grit** [comment]
I can not think of a reason the rest of the flow would not be needed unless we did not enable the GPS at all. The challenge is in switching modes from GPS to LTE and managing the fact that Nordic samples offload DTLS to the modem but Golioth currently requires DTLS running in the host controller.
